//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKIbyAkhremchik.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlbumPhoto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlbumPhoto()
        {
            this.GalleryPhotos = new HashSet<GalleryPhoto>();
        }
    
        public int PhotosId { get; set; }
        public string Name { get; set; }
        public string url1 { get; set; }
        public string url2 { get; set; }
        public string url3 { get; set; }
        public string url4 { get; set; }
        public string url5 { get; set; }
        public string url6 { get; set; }
        public string url7 { get; set; }
        public string url8 { get; set; }
        public string url9 { get; set; }
        public string url10 { get; set; }
        public string url11 { get; set; }
        public string url12 { get; set; }
        public string url13 { get; set; }
        public string url14 { get; set; }
        public string url15 { get; set; }
        public string url16 { get; set; }
        public string url17 { get; set; }
        public string url18 { get; set; }
        public string url19 { get; set; }
        public string url20 { get; set; }
        public string url21 { get; set; }
        public string url22 { get; set; }
        public string url23 { get; set; }
        public string url24 { get; set; }
        public string url25 { get; set; }
        public string url26 { get; set; }
        public string url27 { get; set; }
        public string url28 { get; set; }
        public string url29 { get; set; }
        public string url30 { get; set; }
        public string url31 { get; set; }
        public string url32 { get; set; }
        public string url33 { get; set; }
        public string url34 { get; set; }
        public string url35 { get; set; }
        public string url36 { get; set; }
        public string url37 { get; set; }
        public string url38 { get; set; }
        public string url39 { get; set; }
        public string url40 { get; set; }
        public string url41 { get; set; }
        public string url42 { get; set; }
        public string url43 { get; set; }
        public string url44 { get; set; }
        public string url45 { get; set; }
        public string url46 { get; set; }
        public string url47 { get; set; }
        public string url48 { get; set; }
        public string url49 { get; set; }
        public string url50 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GalleryPhoto> GalleryPhotos { get; set; }
    }
}
