//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKIbyAkhremchik.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GKI_DataEntities : DbContext
    {
        public GKI_DataEntities()
            : base("name=GKI_DataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlbumPhoto> AlbumPhotoes { get; set; }
        public virtual DbSet<GalleryPhoto> GalleryPhotoes { get; set; }
        public virtual DbSet<GalleryVideo> GalleryVideos { get; set; }
        public virtual DbSet<gkiGraduate> gkiGraduates { get; set; }
        public virtual DbSet<gkiParent> gkiParents { get; set; }
        public virtual DbSet<gkiProfile> gkiProfiles { get; set; }
        public virtual DbSet<gkiRole> gkiRoles { get; set; }
        public virtual DbSet<gkiStudent> gkiStudents { get; set; }
        public virtual DbSet<gkiTeacher> gkiTeachers { get; set; }
        public virtual DbSet<gkiUser> gkiUsers { get; set; }
        public virtual DbSet<gkiWorker> gkiWorkers { get; set; }
        public virtual DbSet<NewsArt> NewsArts { get; set; }
        public virtual DbSet<NewsEvent> NewsEvents { get; set; }
        public virtual DbSet<NewsMusical> NewsMusicals { get; set; }
        public virtual DbSet<NewsSchool> NewsSchools { get; set; }
        public virtual DbSet<qCity> qCities { get; set; }
        public virtual DbSet<qDepartment> qDepartments { get; set; }
        public virtual DbSet<qDescipline> qDesciplines { get; set; }
        public virtual DbSet<qGroup> qGroups { get; set; }
        public virtual DbSet<qLanguage> qLanguages { get; set; }
        public virtual DbSet<qProfession> qProfessions { get; set; }
        public virtual DbSet<qSex> qSexes { get; set; }
        public virtual DbSet<qSpecialization> qSpecializations { get; set; }
        public virtual DbSet<qWork> qWorks { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
