//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKIbyAkhremchik.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gkiGraduate
    {
        public int GraduatesId { get; set; }
        public string Name { get; set; }
        public string Lastname { get; set; }
        public string Secondname { get; set; }
        public string Photo { get; set; }
        public string Smalldescription { get; set; }
        public string Description { get; set; }
    }
}
