//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKIbyAkhremchik.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gkiProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gkiProfile()
        {
            this.gkiUsers = new HashSet<gkiUser>();
        }
    
        public int ProfileId { get; set; }
        public string Avatar { get; set; }
        public string Thumb { get; set; }
        public Nullable<decimal> Mobile { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Day { get; set; }
        public string About { get; set; }
        public string Activity { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> SexId { get; set; }
    
        public virtual qCity qCity { get; set; }
        public virtual qLanguage qLanguage { get; set; }
        public virtual qSex qSex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gkiUser> gkiUsers { get; set; }
    }
}
