//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKIbyAkhremchik.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gkiStudent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gkiStudent()
        {
            this.gkiParents = new HashSet<gkiParent>();
        }
    
        public int StudentId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> SpecializationId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gkiParent> gkiParents { get; set; }
        public virtual gkiUser gkiUser { get; set; }
        public virtual qGroup qGroup { get; set; }
        public virtual qSpecialization qSpecialization { get; set; }
    }
}
