//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKIbyAkhremchik.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gkiTeacher
    {
        public int TeacherId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> DesciplineId { get; set; }
        public Nullable<int> ProfessionId { get; set; }
        public Nullable<int> WorkId { get; set; }
    
        public virtual gkiUser gkiUser { get; set; }
        public virtual qDescipline qDescipline { get; set; }
        public virtual qProfession qProfession { get; set; }
        public virtual qWork qWork { get; set; }
    }
}
