//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKIbyAkhremchik.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsMusical
    {
        public int NewsMusicalId { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Img_Title { get; set; }
        public string SmallText { get; set; }
        public string FullText { get; set; }
        public Nullable<int> GalleryPhotoId { get; set; }
        public Nullable<int> GalleryVideoId { get; set; }
    
        public virtual GalleryVideo GalleryVideo { get; set; }
        public virtual GalleryPhoto GalleryPhoto { get; set; }
    }
}
